//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserLoginDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 代码_电子住院证
    {
        public int 流水号 { get; set; }
        public Nullable<int> 就诊ID { get; set; }
        public string 出生地 { get; set; }
        public string 二级科室 { get; set; }
        public string 入院科别 { get; set; }
        public string 关系 { get; set; }
        public string 关系电话 { get; set; }
        public string 出生日期 { get; set; }
        public string 医生签名 { get; set; }
        public string 婚姻状况 { get; set; }
        public string 家庭住址 { get; set; }
        public string 工作单位 { get; set; }
        public string 性别 { get; set; }
        public string 病人姓名 { get; set; }
        public string 病人性质 { get; set; }
        public string 病区 { get; set; }
        public string 职业 { get; set; }
        public string 联系人姓名 { get; set; }
        public string 诊疗小组 { get; set; }
        public string 身份证号 { get; set; }
        public string 门急诊诊断 { get; set; }
        public string 国籍2 { get; set; }
        public Nullable<int> 年龄 { get; set; }
        public string 电话 { get; set; }
        public Nullable<int> 第几次住院 { get; set; }
        public Nullable<int> 邮编 { get; set; }
        public string ICDM { get; set; }
        public string 医生工号 { get; set; }
    }
}
